name: Building Package using Conda

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      #max-parallel: 5
      matrix:
        os: [ubuntu-latest, macos-latest]
        env:
          - CONDA_PY:37
            CONDA_NPY:111   
          - CONDA_PY:38 
            CONDA_NPY:116
          - CONDA_PY:39 
            CONDA_NPY:119

    environment: anaconda_build

    steps:
    - uses: actions/checkout@v2

    - name: Add conda to system path
      run: |
        # Add conda to system path
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH

    - name: Setup conda
      run: |
        # Setup conda
        sudo conda config --add channels conda-forge
        sudo conda config --add channels fredboudon
        sudo conda config --set always_yes yes
        sudo conda config --set remote_read_timeout_secs 600
        sudo conda config --set auto_update_conda False
        sudo conda install conda-build anaconda-client

    - name: Build and Deploy
      env:
          CONDA_PY: ${{ matrix.env.CONDA_PY }}
          CONDA_NPY: ${{ matrix.env.CONDA_NPY }}
          ANACONDA_LOGIN: ${{ secrets.ANACONDA_LOGIN }}
          ANACONDA_OWNER: ${{ secrets.ANACONDA_OWNER }}
          ANACONDA_PASSWORD: ${{ secrets.ANACONDA_PASSWORD }}
      run: |
        # Build and Deploy
        echo "CONDA_PY:", $CONDA_PY
        echo "CONDA_NPY:", $CONDA_NPY
        echo "ANACONDA_OWNER:", $ANACONDA_OWNER
        sudo conda build . 
        if [ $? -eq 0 ]; then
          yes | anaconda login --password $ANACONDA_PASSWORD --username $ANACONDA_LOGIN
          # anaconda upload `conda build . --output` -u $ANACONDA_OWNER --no-progress
        fi

