name: Building Package using Conda

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_CMD_PREFIX: "conda build . --no-test --python="


jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      #max-parallel: 5
      matrix:
        os: [ macos-latest, ubuntu-latest]
        env:
          - CONDA_PY: "3.8" 
          - CONDA_PY: "3.9" 
          - CONDA_PY: "3.10" 

    environment: anaconda_build

    steps:
    - uses: actions/checkout@v2

    - name: Setup miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
          miniconda-version: "latest"
          auto-update-conda: true
          channels: conda-forge, fredboudon
          auto-activate-base: true
          activate-environment: ""
          conda-build-version: "*"
          mamba-version: "*"

    - name: Setup anaconda-client
      run: |
        echo "Install anaconda-client"
        sudo conda activate base
        sudo conda install -y -q anaconda-client


    - name: Build 
      id: build
      env:
          CONDA_PY: ${{ matrix.env.CONDA_PY }}
          BUILD_CMD: "${{ env.BUILD_CMD_PREFIX }}${{ matrix.env.CONDA_PY }}"
      run: |
        # Build
        if [[ "$CONDA_PY" = "" ]]; then
          echo "CONDA_PY is not defined"
          exit -1
        fi

        sudo conda activate base
        $BUILD_CMD

    - name: Set UUID
      id: generate-uuid
      uses: filipstefansson/uuid-action@v1

    - name: Login
      env:
          ANACONDA_LOGIN: ${{ secrets.ANACONDA_LOGIN }}
          ANACONDA_PASSWORD: ${{ secrets.ANACONDA_PASSWORD }}
          SESSION_UID: ${{ steps.generate-uuid.outputs.uuid }}
      run: |
        # Login
        if [[ "$ANACONDA_LOGIN" = "" ]]; then
          echo "ANACONDA_LOGIN is not defined"
          exit -1
        fi
        if [[ "$SESSION_UID" = "" ]]; then
          echo "SESSION_UID is not defined"
          exit -1
        fi

        echo "SESSION_UID=$SESSION_UID"

        sudo conda activate base

        anaconda login --username $ANACONDA_LOGIN --password $ANACONDA_PASSWORD --hostname $SESSION_UID

    - name: Deploy
      env:
          ANACONDA_OWNER: ${{ secrets.ANACONDA_OWNER }}
          BUILD_OUTPUT_CMD: "${{ env.BUILD_CMD_PREFIX }}${{ matrix.env.CONDA_PY }} --output"
      run: |
        # Deploy
        if [[ "$ANACONDA_OWNER" = "" ]]; then
          echo "ANACONDA_OWNER is not defined"
          exit -1
        fi

        sudo conda activate base

        export PACKAGE_NAME=`$BUILD_OUTPUT_CMD`

        if [[ "$BUILD_OUTPUT" = "" ]]; then
          echo "PACKAGE_NAME is not defined"
          exit -1
        fi

        anaconda upload --skip-existing $PACKAGE_NAME -u $ANACONDA_OWNER --no-progress

